stages:
  - deploy
  - run

include:
  - '.gitlabcicd/write_to_local_log_file.yml'

variables:
  DESTINATION_PATH: "$HOMEDIR/$CI_PROJECT_NAME/glcicd/$ENVIRONMENT"
  LOG_PATH: "$HOMEDIR/logs_private/$CI_PROJECT_NAME/$ENVIRONMENT"
  ENVIRONMENT: "benchmark" # can be set as pipeline variable
  HOMEDIR: "~" # default homedir works in most cases but sometimes it needs to be explicitely evaluated

before_script:
  - echo "path $DESTINATION_PATH"
  - mkdir -p ~/.ssh
  - echo $SSH_KEY | base64 --decode > ~/.ssh/id_rsa # must decode base64 as key is stored as base64 in gitlab var
  - chmod 600 ~/.ssh/id_rsa

create environment directory:
  stage: deploy
  environment:
    name: $ENVIRONMENT 
  variables:
    PATHS: "$DESTINATION_PATH+++$LOG_PATH"
    HOMEDIR: "$(eval echo \"~$USER\")" # ~ cannot be expanded in this command therefore we need to evaluate it
  script:
    - echo "cre env"
    - |
      ssh -o StrictHostKeyChecking=no -T -i ~/.ssh/id_rsa "${USER_ON_HOST}" "sh -c '
      for path in \$(echo \"$PATHS\" | tr \"+++\" \"\n\"); do
        echo \"\$path\" && mkdir -p \$path; done
      '"

log deployment start:
  extends: .write to local log file
  stage: deploy
  environment:
    name: $ENVIRONMENT
  when: on_success
  needs:
    - job: create environment directory

transfer env vars to remote:
  stage: deploy  
  environment:
    name: $ENVIRONMENT
  when: on_success
  needs:
    - job: create environment directory
  script:
    - echo "trans env"
    -  |
      echo "export PORT=$(echo $PORT | base64 --decode)" >> ~/env
      scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ~/env "${USER_ON_HOST}":"$DESTINATION_PATH/env.var"

log env transfer:
  stage: deploy
  environment:
    name: $ENVIRONMENT
  when: on_success
  needs:
    - job: transfer env vars to remote
  script:
    - |
      ssh -o StrictHostKeyChecking=no -T -i ~/.ssh/id_rsa "${USER_ON_HOST}" "sh -c '
      echo \"$(date +'%Y-%m-%d_%T'): Environment variables have been set.\" >> $LOG_PATH/deployment'"


copy app to remote:
  stage: deploy
  when: on_success
  needs:
    - job: create environment directory
  script:
    - scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa * "${USER_ON_HOST}":"$DESTINATION_PATH"

log deployment successful:
  stage: deploy
  environment:
    name: $ENVIRONMENT
  when: on_success
  needs:
    - job: copy app to remote
  script:
    |
    ssh -o StrictHostKeyChecking=no -T -i ~/.ssh/id_rsa "${USER_ON_HOST}" "sh -c '
    echo \"$(date +'%Y-%m-%d_%T'): Deployment to $DESTINATION_PATH was successful.\" >> $LOG_PATH/deployment
    echo \"===\" >> $LOG_PATH/deployment'"

run app:
  stage: deploy
  when: manual
  script:
    - echo "path $DESTINATION_PATH"
